Fixed compile warnings (missing includes and a assignment-instead-of-comparison) in examples:
geoclue_map_example.c: In function ‘update_map’:
geoclue_map_example.c:113: warning: implicit declaration of function ‘free’
geoclue_map_example.c: In function ‘update’:
geoclue_map_example.c:131: warning: implicit declaration of function ‘malloc’
geoclue_map_example.c:131: warning: incompatible implicit declaration of built-in function ‘malloc’
geoclue_map_example.c: In function ‘image_size_callback’:
geoclue_map_example.c:190: warning: suggest parentheses around assignment used as truth value
geoclue_find_example.c: In function ‘main’:
geoclue_find_example.c:78: warning: implicit declaration of function ‘free’
geoclue_find_example.c:89: warning: unused variable ‘id’
geoclue_find_example.c:62: warning: unused variable ‘retncode’