Compiler warning-fixes in geoclue/, mostly missing #includes
position.c: In function 'geoclue_position_set_position_callback':
position.c:58: warning: control reaches end of non-void function
position.c: In function 'geoclue_position_init':
position.c:177: warning: implicit declaration of function 'free'
find.c:43: warning: initialization makes integer from pointer without a cast
find.c: In function 'geoclue_find_init':
find.c:175: warning: implicit declaration of function 'free'
map.c: In function 'geoclue_map_init':
map.c:199: warning: implicit declaration of function 'free'
map_gtk_layout.c: In function 'geoclue_map_gtk_layout_new_corners':
map_gtk_layout.c:126: warning: implicit declaration of function 'geoclue_map_find_zoom_level'
map_gtk_layout.c: In function 'geoclue_map_gtk_layout_set_property':
map_gtk_layout.c:389: warning: implicit declaration of function 'geoclue_map_max_zoom'
map_gtk_layout.c: In function 'geoclue_map_gtk_layout_add_widget':
map_gtk_layout.c:498: warning: implicit declaration of function 'geoclue_map_latlong_to_offset'
map_gtk_layout.c: In function 'geoclue_map_gtk_layout_zoom_in':
map_gtk_layout.c:569: warning: implicit declaration of function 'geoclue_map_gtk_get_gdk_pixbuf'
map_gtk_layout.c: In function 'geoclue_map_gtk_layout_button_realease':
map_gtk_layout.c:630: warning: implicit declaration of function 'geoclue_map_offset_to_latlong'
geoclue_master.c: In function ‘geoclueserver_add_backend’:
geoclue_master.c:50: warning: implicit declaration of function ‘g_open’
geoclue_master.c:54: warning: implicit declaration of function ‘malloc’
geoclue_master.c:54: warning: incompatible implicit declaration of built-in function ‘malloc’
geoclue_master.c:87: warning: implicit declaration of function ‘free’
geoclue_master.c: In function ‘geoclue_master_get_all_position_providers’:
geoclue_master.c:219: warning: incompatible implicit declaration of built-in function ‘malloc’
geoclue_master.c: In function ‘geoclue_master_get_all_map_providers’:
geoclue_master.c:262: warning: incompatible implicit declaration of built-in function ‘malloc’