Added missing includes, removed unused variables, fixed indenting and whitespace issues in backend/*
geoclue_map_server_yahoo.c: In function ‘geoclue_map_map_thread’:
geoclue_map_server_yahoo.c:256: warning: unused variable ‘fd’
geoclue_map_server_yahoo.c: In function ‘main’:
geoclue_map_server_yahoo.c:528: warning: unused variable ‘request_name_result’
geoclue_position_server_manual.c: In function ‘main’:
geoclue_position_server_manual.c:269: warning: implicit declaration of function ‘geoclue_map_init’
geoclue_geocode_server_yahoo.c: In function ‘geoclue_geocode_to_lat_lon’:
geoclue_geocode_server_yahoo.c:191: warning: unused variable ‘pngurl’
geoclue_geocode_server_yahoo.c:153: warning: unused variable ‘fd’
geoclue_geocode_server_yahoo.c: In function ‘geoclue_geocode_free_text_to_lat_lon’:
geoclue_geocode_server_yahoo.c:301: warning: unused variable ‘pngurl’
geoclue_geocode_server_yahoo.c:263: warning: unused variable ‘fd’
geoclue_geocode_server_yahoo.c: In function ‘main’:
geoclue_geocode_server_yahoo.c:393: warning: unused variable ‘request_name_result’
geoclue_position_server_hostip.c: In function ‘geoclue_position_current_position’:
geoclue_position_server_hostip.c:206: warning: implicit declaration of function ‘strcmp’
geoclue_position_server_hostip.c:186: warning: unused variable ‘pngurl’
geoclue_position_server_hostip.c:148: warning: unused variable ‘fd’
geoclue_position_server_hostip.c: In function ‘main’:
geoclue_position_server_hostip.c:314: warning: unused variable ‘request_name_result’
geoclue_position_server_gpsd.c: In function ‘main’:
geoclue_position_server_gpsd.c:252: warning: unused variable ‘request_name_result’